#!/bin/bash
# Copyright 2026 Nick Brassel (@tzarc)
# SPDX-License-Identifier: GPL-2.0-or-later

# Default conf location is different on windows - force unless the user has already done so
if [[ "$*" != *-C* ]]; then
    EXTRA_ARGS=" -C $(wslpath -m /etc/avrdude.conf)"
fi

avrdude.exe $EXTRA_ARGS "$@"
